#!/usr/bin/env bash

print_help() { cat <<EOS
Usage: ${0##*/} [OPTION] TEXT
Have tachikoma say TEXT

Options:
  --fortune=OPTS             Have tachi say wisdom from fortune
                             Passing this option with ignore any TEXT given
  --ascii=FILE               Use ascii file other than tachi.ascii
  --header=FILE or TEXT      File or text to insert before ascii
  --footer=FILE or TEXT      File or text to add after ascii

  --help                     Print this page
EOS
}

main() {
  unset fortune
  unset ascii
  unset header
  unset footer

  cd $(dirname $(realpath $0))

  while (( $# )); do
    case "$1" in
      --fortune=*)
        read -ra fortune <<<"${1#*=}"
      ;;
      --ascii=*)
        ascii="${1#*=}"
        assert_file "$ascii"
      ;;
      --header=*)
        header="$(file_or_text "$1")"
      ;;
      --footer=*)
        footer="$(file_or_text "$1")"
      ;;
      --help)
        print_help
        exit
      ;;
      --) shift; break;;
      -*) bail "Invalid option: $1";;
      *) break;;
    esac
    shift
  done

  assert_file "${ascii:=/usr/share/tachisay/tachi.ascii}"

  asciisay="asciisay"
  if ! command -v "$asciisay" >/dev/null 2>&1; then
    asciisay="./asciisay"
    [[ -x "$asciisay" ]] || bail "asciisay not found"
  fi

  text=$(
    if [[ -z "$fortune" ]]; then
      echo "${*:-"...."}"
    else
      fortune "${fortune[@]}"
    fi
  )

  dump "$header"
  $asciisay <(echo "$text") "$ascii"
  dump "$footer"
}

assert_file() {
  [[ -s "$1" ]] || bail "${2:-"$1 is not a file or is empty"}"
}

file_or_text() {
  in="${1#*=}"
  if [[ -s "$in" ]]; then
    realpath "$in"
  else
    echo "$in"
  fi
}

dump() {
  [[ -n "$1" ]] || return

  if [[ -s "$1" ]]; then
    cat "$1"
  else
    echo -e "$1"
  fi
}

bail() { # {{{1
  printf "%s\n" >&2
  exit 1
}

main "$@" # {{{1
